import { PROJECT_SCHEMA_VERSION, type RobotModel } from "./types.js";

/** Reference robot wiring used in tests and the web UI sample loader. */
export function createHealthyRobotModel(): RobotModel {
  return {
    schemaVersion: PROJECT_SCHEMA_VERSION,
    id: "robot-1",
    name: "Healthy Robot",
    devices: [
      { id: "battery-1", type: "Battery", position: { x: 60, y: 320 } },
      {
        id: "pdh-1",
        type: "PDH",
        metadata: { canId: 1 },
        position: { x: 380, y: 320 },
      },
      {
        id: "vrm-1",
        type: "VRM",
        position: { x: 720, y: 560 },
      },
      {
        id: "rio-1",
        type: "RoboRIO",
        metadata: { ipAddress: "10.6.91.2" },
        position: { x: 720, y: 80 },
      },
      {
        id: "radio-1",
        type: "Radio",
        metadata: { ipAddress: "10.6.91.1" },
        position: { x: 1060, y: 560 },
      },
      {
        id: "spark-1",
        type: "SparkMax",
        label: "Drive Left",
        metadata: { canId: 2 },
        position: { x: 1060, y: 80 },
      },
      {
        id: "coder-1",
        type: "CANcoder",
        metadata: { canId: 3 },
        position: { x: 1400, y: 80 },
      },
      {
        id: "limelight-1",
        type: "Limelight",
        metadata: { ipAddress: "10.6.91.11" },
        position: { x: 1400, y: 560 },
      },
    ],
    connections: [
      {
        id: "battery-pdh-power",
        sourceDevice: "battery-1",
        sourcePort: "main_power",
        targetDevice: "pdh-1",
        targetPort: "main_power_in",
      },
      {
        id: "battery-pdh-ground",
        sourceDevice: "battery-1",
        sourcePort: "ground",
        targetDevice: "pdh-1",
        targetPort: "ground_in",
      },
      {
        id: "pdh-rio-power",
        sourceDevice: "pdh-1",
        sourcePort: "channel_0",
        targetDevice: "rio-1",
        targetPort: "power_in",
      },
      {
        id: "pdh-rio-ground",
        sourceDevice: "pdh-1",
        sourcePort: "ground_bus",
        targetDevice: "rio-1",
        targetPort: "ground",
      },
      {
        id: "pdh-spark-power",
        sourceDevice: "pdh-1",
        sourcePort: "channel_1",
        targetDevice: "spark-1",
        targetPort: "power_in",
      },
      {
        id: "pdh-spark-ground",
        sourceDevice: "pdh-1",
        sourcePort: "ground_bus",
        targetDevice: "spark-1",
        targetPort: "ground",
      },
      {
        id: "pdh-coder-power",
        sourceDevice: "pdh-1",
        sourcePort: "channel_2",
        targetDevice: "coder-1",
        targetPort: "power_in",
      },
      {
        id: "pdh-coder-ground",
        sourceDevice: "pdh-1",
        sourcePort: "ground_bus",
        targetDevice: "coder-1",
        targetPort: "ground",
      },
      {
        id: "pdh-limelight-power",
        sourceDevice: "pdh-1",
        sourcePort: "channel_3",
        targetDevice: "limelight-1",
        targetPort: "power_in",
      },
      {
        id: "pdh-limelight-ground",
        sourceDevice: "pdh-1",
        sourcePort: "ground_bus",
        targetDevice: "limelight-1",
        targetPort: "ground",
      },
      {
        id: "pdh-vrm-power",
        sourceDevice: "pdh-1",
        sourcePort: "vrm_out",
        targetDevice: "vrm-1",
        targetPort: "power_in",
      },
      {
        id: "pdh-vrm-ground",
        sourceDevice: "pdh-1",
        sourcePort: "ground_bus",
        targetDevice: "vrm-1",
        targetPort: "ground",
      },
      {
        id: "vrm-radio-power",
        sourceDevice: "vrm-1",
        sourcePort: "12v_2a_0",
        targetDevice: "radio-1",
        targetPort: "power_in",
      },
      {
        id: "vrm-radio-ground",
        sourceDevice: "vrm-1",
        sourcePort: "ground_12v_2a_0",
        targetDevice: "radio-1",
        targetPort: "ground",
      },
      {
        id: "rio-pdh-can",
        sourceDevice: "rio-1",
        sourcePort: "can_bus",
        targetDevice: "pdh-1",
        targetPort: "can_bus",
      },
      {
        id: "pdh-spark-can",
        sourceDevice: "pdh-1",
        sourcePort: "can_bus",
        targetDevice: "spark-1",
        targetPort: "can_bus",
      },
      {
        id: "spark-coder-can",
        sourceDevice: "spark-1",
        sourcePort: "can_bus",
        targetDevice: "coder-1",
        targetPort: "can_bus",
      },
      {
        id: "radio-rio-eth",
        sourceDevice: "radio-1",
        sourcePort: "eth_poe",
        targetDevice: "rio-1",
        targetPort: "eth_0",
      },
      {
        id: "radio-limelight-eth",
        sourceDevice: "radio-1",
        sourcePort: "eth_aux",
        targetDevice: "limelight-1",
        targetPort: "eth_0",
      },
    ],
  };
}
