import battery from '../../../../component-images/battery/battery.png';
import breaker120 from '../../../../component-images/breaker120/breaker120.png';
import cancoder from '../../../../component-images/cancoder/cancoder.png';
import ethswitch from '../../../../component-images/ethswitch/ethswitch.png';
import limelight from '../../../../component-images/limelight/limelight.png';
import orangepi from '../../../../component-images/orangepi/orangepi.png';
import pdh from '../../../../component-images/pdh/pdh.png';
import pdp from '../../../../component-images/pdp/pdp.png';
import photonvision from '../../../../component-images/photonvision/photonvision.png';
import pigeon2 from '../../../../component-images/pigeon2/pigeon2.png';
import radio from '../../../../component-images/radio/radio.png';
import roborio from '../../../../component-images/roborio/roborio.png';
import sparkflex from '../../../../component-images/sparkflex/sparkflex.png';
import sparkmax from '../../../../component-images/sparkmax/sparkmax.png';
import systemcore from '../../../../component-images/systemcore/systemcore.png';
import talonfx from '../../../../component-images/talonfx/talonfx.png';
import vrm from '../../../../component-images/vrm/vrm.png';

/**
 * Flat diagrams generated by component-images/, keyed by registry device type.
 * Regenerate the PNGs with `python3 component-images/buildall.py`.
 */
const DEVICE_IMAGES: Record<string, string> = {
  Battery: battery,
  MainBreaker: breaker120,
  CANcoder: cancoder,
  EthernetSwitch: ethswitch,
  Limelight: limelight,
  OrangePi: orangepi,
  PDH: pdh,
  PDP: pdp,
  PhotonVision: photonvision,
  Pigeon2: pigeon2,
  Radio: radio,
  RoboRIO: roborio,
  SparkFlex: sparkflex,
  SparkMax: sparkmax,
  SystemCore: systemcore,
  TalonFX: talonfx,
  VRM: vrm,
};

export function deviceImage(type: string): string | undefined {
  return DEVICE_IMAGES[type];
}
