import type { RobotModelState } from '../hooks/useRobotModel';
import { PORT_TYPE_NAMES } from '../utils/labels';
import { resolveConnectionPortType } from '../utils/wireStyles';
import { PortType } from '@691sim/core';

export function formatConnectionList(state: RobotModelState): string[] {
  const { model, registry } = state;
  return model.connections.map((conn, index) => {
    const srcDevice = model.devices.find((d) => d.id === conn.sourceDevice);
    const portType =
      resolveConnectionPortType(
        registry,
        conn.sourceDevice,
        srcDevice?.type ?? '',
        conn.sourcePort,
      ) ?? PortType.POWER;
    const hidden = portType === PortType.GROUND ? ' (auto ground)' : '';
    return `${index + 1}. [${conn.id}] ${conn.sourceDevice}.${conn.sourcePort} → ${conn.targetDevice}.${conn.targetPort} (${PORT_TYPE_NAMES[portType]}${hidden})`;
  });
}

export async function exportCircuitPdf(state: RobotModelState): Promise<void> {
  const [{ default: html2canvas }, { jsPDF }] = await Promise.all([
    import('html2canvas'),
    import('jspdf'),
  ]);

  const canvasEl = document.getElementById('circuit-canvas');
  if (!canvasEl) {
    throw new Error('Circuit canvas not found');
  }

  const snapshot = await html2canvas(canvasEl, {
    backgroundColor: '#ffffff',
    scale: 2,
    logging: false,
    useCORS: true,
  });

  const pdf = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'letter' });
  const margin = 40;
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const contentWidth = pageWidth - margin * 2;

  pdf.setFontSize(18);
  pdf.text('691SIM Circuit Report', margin, margin);
  pdf.setFontSize(11);
  pdf.setTextColor(80);
  pdf.text(`${state.model.name} — ${new Date().toLocaleString()}`, margin, margin + 18);
  pdf.setTextColor(0);

  const imgRatio = snapshot.height / snapshot.width;
  const imgWidth = contentWidth;
  const imgHeight = imgWidth * imgRatio;
  const imgData = snapshot.toDataURL('image/png');
  pdf.addImage(imgData, 'PNG', margin, margin + 30, imgWidth, Math.min(imgHeight, 280));

  let y = margin + 30 + Math.min(imgHeight, 280) + 24;

  pdf.setFontSize(13);
  pdf.text('Wire Connection Checklist', margin, y);
  y += 16;
  pdf.setFontSize(9);

  const connections = formatConnectionList(state);
  if (connections.length === 0) {
    pdf.text('No connections.', margin, y);
    y += 14;
  } else {
    for (const line of connections) {
      if (y > pageHeight - margin) {
        pdf.addPage();
        y = margin;
      }
      pdf.text(`☐ ${line}`, margin, y);
      y += 12;
    }
  }

  y += 10;
  pdf.setFontSize(13);
  if (y > pageHeight - margin - 40) {
    pdf.addPage();
    y = margin;
  }
  pdf.text('Diagnostics / Errors', margin, y);
  y += 16;
  pdf.setFontSize(9);

  const errors = state.verification.diagnostics;
  if (errors.length === 0) {
    pdf.setTextColor(0, 128, 0);
    pdf.text('No issues found. Run Verify before exporting for latest results.', margin, y);
  } else {
    for (const diag of errors) {
      if (y > pageHeight - margin) {
        pdf.addPage();
        y = margin;
      }
      const prefix = diag.severity === 2 ? '[ERROR]' : diag.severity === 1 ? '[WARN]' : '[INFO]';
      pdf.setTextColor(diag.severity === 2 ? 180 : 0, diag.severity === 2 ? 0 : 0, 0);
      const wrapped = pdf.splitTextToSize(`${prefix} ${diag.code ?? ''}: ${diag.message}`, contentWidth);
      pdf.text(wrapped, margin, y);
      y += wrapped.length * 11 + 4;
    }
  }

  pdf.setTextColor(100);
  pdf.setFontSize(8);
  pdf.text('Generated by 691SIM — https://github.com/asaxena23757/691SIM', margin, pageHeight - 20);

  pdf.save(`${state.model.name.replace(/\s+/g, '-').toLowerCase()}-circuit.pdf`);
}
